djangoProject-master/store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('storeProducts.urls', namespace="store")),
    path('users/', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoProject-master/store/storeProducts/urls.py
from django.urls import path, include

from . import views

app_name = 'storeProducts'

urlpatterns = [
    path('', views.index, name='index'),
    path('products/', views.products, name='products'),
    path('products/category/<int:category_id>/', views.products, name='category'),
    path('baskets/add/<int:product_id>/', views.basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', views.basket_remove, name='basket_remove'),
]

djangoProject-master/store/storeProducts/models.py
from django.db import models
from users.models import User

class ProductCategory(models.Model):
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self) :
        return self.name



class Product(models.Model) :
    name = models.CharField(max_length=256)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='products_image')
    category = models.ForeignKey(to=ProductCategory, on_delete=models.CASCADE)

    def __str__(self) :
        return self.name


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    products = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self) :
        return f'Корзина товаров для {self.user.username}'

    def sum(self):
        return self.products.price * self.quantity

djangoProject-master/store/storeProducts/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import *
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage

def index(request):
    context = {
        'title': 'storeApp',
        'username': 'Adil Zhapar',
        'is_promotion': True
    }
    return render(request, 'storeProducts/index.html', context)


def products(request, category_id=None):
    if category_id:
        category = ProductCategory.objects.get(id = category_id)
        products = Product.objects.filter(category = category)
    else:
        products = Product.objects.all()

    paginator = Paginator(products, 3)
    page_number = request.GET.get('page', 1)

    try:
        page = paginator.page(page_number)
    except EmptyPage:
        page = paginator.page(paginator.num_pages)

    context = {
        'title' : 'storeApp',
        'products' : page,
        'categories' : ProductCategory.objects.all(),
    }
    return render(request, 'storeProducts/products.html', context)

@login_required
def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, products=product)
    
    if not baskets.exists():
        Basket.objects.create(user=request.user, products=product, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

djangoProject-master/store/storeProducts/templates/storeProducts/basket.html
{% if baskets %}

    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
            Корзина <span class="badge badge-secondary badge-pill">{{ total_quantity }}</span>
    </h4>

    {% for basket in baskets %}
        <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">{{ basket.products.name }}</h5>
                        <p class="card-text">{{ basket.products.description }}</p>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item bg-light">
                            <div class="row text-center">
                                <div class="col-lg-4">
                                    <input name="basketID" type="number" class="form-control"
                                           value="{{ basket.quantity }}" min="0">
                                </div>
                                <div class="col-lg-4">{{ basket.sum }}</div>
                                <div class="col-lg-4">
                                    <a href="{% url 'storeProducts:basket_remove' basket.id %}">
                                        <i class="fas fa-trash"></i>
                                    </a>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
    {% endfor %}

    <div class="card mb-3">
                    <div class="card-footer">
                        <p class="float-left">Итого</p>
                        <h4 class="float-right">{{ total_sum }}</h4>
                    </div>
                </div>
    <a class="btn btn-success btn-lg float-right" href="../orders/order-create.html">
                Оформить заказ
            </a>
{% else %}
    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
            Корзина пуста
    </h4>
{% endif %}

djangoProject-master/store/storeProducts/templates/storeProducts/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{title}}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'vendor/css/index.css' %}" rel="stylesheet">
 
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="/store">Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="products">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/users/login">Войти <i class="fas fa-sign-in-alt"></i></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user-circle"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item" href="/users/profile">Профиль</a>
                        </li>
                        <li><a class="dropdown-item" href="/orders/orders">Заказы</a></li>
                        <li><a class="dropdown-item" href="#">Админ-панель</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item" href="#">
                                Выйти
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<section>
    <!--    <div class="alert alert-light text-center" role="alert">-->
    <!--        Информационное сообщение-->
    <!--    </div>-->
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">Store</h1>
                <p>
                    Новые образы и лучшие бренды на Store.
                    Бесплатная доставка по всему миру! 
                    {% if is_promotion %}
                    Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                    {% endif %}
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="products">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>

<!-- Bootstrap core JavaScript -->
<script src="/static/vendor/jquery/jquery.min.js"></script>
<script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src="/static/vendor/fontawesome/fontawesome-icons.js" crossorigin="anonymous"></script>

</body>

</html>

djangoProject-master/store/storeProducts/templates/storeProducts/products.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'vendor/css/index.css' %}" rel="stylesheet">

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="/store">Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/users/login">Войти <i class="fas fa-sign-in-alt"></i></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user-circle"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item" href="/users/profile">Профиль</a>
                        </li>
                        <li><a class="dropdown-item" href="orders/orders.html">Заказы</a></li>
                        <li><a class="dropdown-item" href="#">Админ-панель</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item" href="#">
                                Выйти
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Store</h1>
            <div class="list-group">
                {% for category in categories %}
                 <a href="{% url 'storeProducts:category' category.id %}" class="list-group-item">{{ category.name }}</a>
                {% endfor %}

            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-1.jpg" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-2.jpg" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-3.jpg" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
                {% for product in products %}
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#">
                            <img class="card-img-top"
                            src = "{% if product.image %}
                                    {{product.image.url }}
                                {% else %}
                                    {% static 'vendor/img/users/default_avatar.jpg' %}
                                {% endif %}"
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">{{ product.name }}</a>
                            </h4>
                            <h5>{{ product.price }}</h5>
                            <p class="card-text">{{ product.description }}</p>
                        </div>
                        <div class="card-footer text-center">
                            <a class="btn btn-outline-success" href="{% url 'storeProducts:basket_add' product.id %}">
                                Отправить в корзину
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}




            </div>

            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    {% if products.has_previous %}
                    <li class="page-item ">
                        <a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a>
                    </li>
                    {% endif %}
                    
                    <li class="page-item"><a class="page-link" href="#">Page {{ products.number }} of {{ products.paginator.num_pages }}</a></li>
                    
                    {% if products.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ products.next_page_number }}">Next</a>
                    </li>
                    {% endif %}

                </ul>
            </nav>


        </div>

    </div>

</div>
<!-- /.container -->

<!-- Footer -->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Store 2022</p>
    </div>
    <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
<script src="/static/vendor/jquery/jquery.min.js"></script>
<script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src="/static/vendor/fontawesome/fontawesome-icons.js" crossorigin="anonymous"></script>

</body>

</html>